### ISSUE TITLE
Checking out the Mesh Library

### ISSUE THREAD

**Issue by gabdsg** [NordicPlayground/IOS-nRF-Mesh-Library#11]
Hi! we are trying to setup the light_switch example from nordic and use this iOS app to setup the mesh. However we are unable to make it work? Know its in early stages, but we got to download and configure NRF52 with the example and nothing happens. Any ideas how to proceed? Do you have any working example that we can use in conjunction with the library setup? Thank you!

**Comment by gabdsg** [comment]
Now on proxy_client i'm getting this error: Ignored. Node is not configured.
I checked client_publication_configured() and (pub_addr_handle == DSM_HANDLE_INVALID) is true for every model

**Comment by mostafaberg** [comment]
First of all congratulations on the first issue :)

Secondly, which branch are you working on ? I recommend building from develop as the current initial release is a bit incomplete and there are lots of fixes on dev.

There’s not so much to do besides flashing the sample firmwares, all you need to do is just hit the add button and the provisioning and configuration will take place straight away , then you’ll be able to see the newly provisioned node on the main network view where you can configure it further and view all its information. 

I’ll get back to you again tomorrow morning to see how far you went and if you have any more issues :)

Thanks for the early testing !

**Comment by mostafaberg** [comment]
Do you still have any issues with the library or can we close this now ?

**Comment by gabdsg** [comment]
it works! Thanks

**Comment by mostafaberg** [comment]
That's great news ! glad to hear you sorted things out !
please let us know if there are any new issues or feature requests :)
