### ISSUE TITLE
NRF_ERROR_NO_MEM

### ISSUE THREAD

**Issue by gabdsg** [NordicPlayground/IOS-nRF-Mesh-Library#18]
Hi! We got the mesh working with our custom model. however if we try to send a package multiple times it throws NRF_ERROR_NO_MEM error. Any ideas why this might happen or if there is any workaround?

Thank you!

**Comment by mostafaberg** [comment]
Good morning @gabdsg I would say this is the wrong place to handle it, as this repo is focused only for the iOS library, I would suggest opening a ticket on DevZone as the mesh firmware team can give you a proper answer there :) let us know if you have any other issues related to the iOS library and we'll surely give you all the help needed :)
